const forceStartScene = process.env.FORCE_START_SCENE === '1';
const port = parseInt(process.env.PORT || '7777', 10);
const mapClientRoot = process.env.MAP_CLIENT_ROOT || process.env.CLIENT_ROOT;
const bindHost = process.env.BIND_HOST || '0.0.0.0';
const serverHost = process.env.SERVER_HOST || '127.0.0.1';

// --- Environment / paths ---
export const ENV = {
  BIND_HOST: bindHost,
  SERVER_HOST: serverHost,
  PORT: Number.isInteger(port) && port > 0 ? port : 7777,
  LOG_FILE: process.env.LOG_FILE || 'server.log',
  CHARACTER_STORE_FILE: process.env.CHARACTER_STORE_FILE || 'characters.json',
  COMBAT_PROBE_STATE_FILE: process.env.COMBAT_PROBE_STATE_FILE || 'combat-probe-state.json',
  COMBAT_REFERENCE_ROOT: process.env.COMBAT_REFERENCE_ROOT || 'third_party/shengxiao-server',
  MAP_CLIENT_ROOT: mapClientRoot || null,
} as const;

// --- Protocol framing ---
export const FRAMING = {
  MAX_PACKET_SIZE: 0x4000,
  VALID_FLAG_MASK: 0xe0,
  VALID_FLAG_VALUE: 0x40,
  DEFAULT_FLAGS: 0x40,
  SPECIAL_FLAGS: 0x44,
} as const;

// --- Game command words ---
export const GAME_CMD = {
  LOGIN: 0x03e9,
  POSITION_QUERY: 0x03eb,
  DIALOG: 0x03e7,
  SERVER_RUN: 0x03f1,
  NPC_SHOP: 0x0411,
  ITEM_CONTAINER: 0x03f2,
  ITEM: 0x03f3,
  ITEM_SERVICE: 0x03f8,
  SELF_STATE: 0x03f6,
  QUEST: 0x03ff,
  SCRIPT_EVENT: 0x0407,
  FIGHT_CLIENT: 0x0406,
  FIGHT_STATE: 0x03ec,
  FIGHT_ACTION: 0x03ed,
  FIGHT_RESULT: 0x03ee,
  FIGHT_TURN: 0x03f0,
  FIGHT_MISC: 0x0453,
  FIGHT_STREAM: 0x03fa,
  ROLE: 0x044c,
  HANDSHAKE: 1,
  PING: 2,
  PONG: 3,
} as const;

// --- Subcommands ---
export const SUB = {
  FIGHT_CONTROL_RING_OPEN: 0x01,
  FIGHT_CONTROL_INIT: 0x02,
  FIGHT_ACTIVE_STATE: 0x03,
  FIGHT_CLIENT_FLEE: 0x02,
  FIGHT_CLIENT_ATTACK_SELECTION: 0x03,
  FIGHT_CLIENT_ITEM_USE: 0x05,
  FIGHT_CLIENT_READY: 0x09,
  FIGHT_CLIENT_DEFEND: 0x0e,
  FIGHT_ENTITY_FLAG_HIDE: 0x33,
  FIGHT_CONTROL_SHOW: 0x34,
  FIGHT_STATE_MODE: 0x64,
  FIGHT_ENCOUNTER_PROBE: 0x65,
  FIGHT_RESULT_VICTORY: 0x66,
  FIGHT_RESULT_DEFEAT: 0x67,
  SPAWN_BATCH: 0x15,
  ITEM_CONTAINER_POSITION: 0x17,
  LINE_SELECT_RESULT: 0x1b,
  REDIRECT_RESULT: 0x0d,
  LOGIN_SERVER_LIST_RESULT: 0x03,
  DIALOG_MESSAGE: 0x01,
  SERVER_RUN_MESSAGE: 0x01,
  SERVER_RUN_CONTEXT: 0x02,
  SERVER_RUN_REST: 0x0f,
  SELF_STATE_APTITUDE: 0x0a,
  SELF_STATE_VALUE_UPDATE: 0x0c,
  SERVER_SCRIPT_IMMEDIATE: 0x7a,
  SERVER_SCRIPT_DEFERRED: 0x7b,
} as const;

// --- World defaults ---
export const WORLD = {
  MAP_ID: 207,
  AREA_ID: 6101,
  ENTITY_TYPE: 0x3e9,
  SPAWN_X: 70,
  SPAWN_Y: 95,
  FORCE_START_SCENE: forceStartScene,
  ENABLE_DIALOG_EXPERIMENT: false,
} as const;

// --- Backward-compatible flat exports (consumed by existing JS modules) ---
module.exports = {
  // Environment
  BIND_HOST: ENV.BIND_HOST,
  SERVER_HOST: ENV.SERVER_HOST,
  PORT: ENV.PORT,
  LOG_FILE: ENV.LOG_FILE,
  CHARACTER_STORE_FILE: ENV.CHARACTER_STORE_FILE,
  COMBAT_PROBE_STATE_FILE: ENV.COMBAT_PROBE_STATE_FILE,
  COMBAT_REFERENCE_ROOT: ENV.COMBAT_REFERENCE_ROOT,
  MAP_CLIENT_ROOT: ENV.MAP_CLIENT_ROOT,

  // Framing
  MAX_PACKET_SIZE: FRAMING.MAX_PACKET_SIZE,
  VALID_FLAG_MASK: FRAMING.VALID_FLAG_MASK,
  VALID_FLAG_VALUE: FRAMING.VALID_FLAG_VALUE,
  DEFAULT_FLAGS: FRAMING.DEFAULT_FLAGS,
  SPECIAL_FLAGS: FRAMING.SPECIAL_FLAGS,

  // Command words
  LOGIN_CMD: GAME_CMD.LOGIN,
  GAME_POSITION_QUERY_CMD: GAME_CMD.POSITION_QUERY,
  GAME_DIALOG_CMD: GAME_CMD.DIALOG,
  GAME_SERVER_RUN_CMD: GAME_CMD.SERVER_RUN,
  GAME_NPC_SHOP_CMD: GAME_CMD.NPC_SHOP,
  GAME_ITEM_CONTAINER_CMD: GAME_CMD.ITEM_CONTAINER,
  GAME_ITEM_CMD: GAME_CMD.ITEM,
  GAME_ITEM_SERVICE_CMD: GAME_CMD.ITEM_SERVICE,
  GAME_SELF_STATE_CMD: GAME_CMD.SELF_STATE,
  GAME_QUEST_CMD: GAME_CMD.QUEST,
  GAME_SCRIPT_EVENT_CMD: GAME_CMD.SCRIPT_EVENT,
  GAME_FIGHT_CLIENT_CMD: GAME_CMD.FIGHT_CLIENT,
  GAME_FIGHT_STATE_CMD: GAME_CMD.FIGHT_STATE,
  GAME_FIGHT_ACTION_CMD: GAME_CMD.FIGHT_ACTION,
  GAME_FIGHT_RESULT_CMD: GAME_CMD.FIGHT_RESULT,
  GAME_FIGHT_TURN_CMD: GAME_CMD.FIGHT_TURN,
  GAME_FIGHT_MISC_CMD: GAME_CMD.FIGHT_MISC,
  GAME_FIGHT_STREAM_CMD: GAME_CMD.FIGHT_STREAM,
  ROLE_CMD: GAME_CMD.ROLE,
  HANDSHAKE_CMD: GAME_CMD.HANDSHAKE,
  PING_CMD: GAME_CMD.PING,
  PONG_CMD: GAME_CMD.PONG,

  // Subcommands
  ITEM_CONTAINER_POSITION_SUBCMD: SUB.ITEM_CONTAINER_POSITION,
  FIGHT_CONTROL_RING_OPEN_SUBCMD: SUB.FIGHT_CONTROL_RING_OPEN,
  FIGHT_CONTROL_INIT_SUBCMD: SUB.FIGHT_CONTROL_INIT,
  FIGHT_ACTIVE_STATE_SUBCMD: SUB.FIGHT_ACTIVE_STATE,
  FIGHT_CLIENT_FLEE_SUBCMD: SUB.FIGHT_CLIENT_FLEE,
  FIGHT_CLIENT_ATTACK_SELECTION_SUBCMD: SUB.FIGHT_CLIENT_ATTACK_SELECTION,
  FIGHT_CLIENT_ITEM_USE_SUBCMD: SUB.FIGHT_CLIENT_ITEM_USE,
  FIGHT_CLIENT_READY_SUBCMD: SUB.FIGHT_CLIENT_READY,
  FIGHT_CLIENT_DEFEND_SUBCMD: SUB.FIGHT_CLIENT_DEFEND,
  FIGHT_ENTITY_FLAG_HIDE_SUBCMD: SUB.FIGHT_ENTITY_FLAG_HIDE,
  FIGHT_CONTROL_SHOW_SUBCMD: SUB.FIGHT_CONTROL_SHOW,
  FIGHT_STATE_MODE_SUBCMD: SUB.FIGHT_STATE_MODE,
  FIGHT_ENCOUNTER_PROBE_SUBCMD: SUB.FIGHT_ENCOUNTER_PROBE,
  FIGHT_RESULT_VICTORY_SUBCMD: SUB.FIGHT_RESULT_VICTORY,
  FIGHT_RESULT_DEFEAT_SUBCMD: SUB.FIGHT_RESULT_DEFEAT,
  GAME_SPAWN_BATCH_SUBCMD: SUB.SPAWN_BATCH,
  LINE_SELECT_RESULT: SUB.LINE_SELECT_RESULT,
  REDIRECT_RESULT: SUB.REDIRECT_RESULT,
  LOGIN_SERVER_LIST_RESULT: SUB.LOGIN_SERVER_LIST_RESULT,
  GAME_DIALOG_MESSAGE_SUBCMD: SUB.DIALOG_MESSAGE,
  SERVER_RUN_MESSAGE_SUBCMD: SUB.SERVER_RUN_MESSAGE,
  SERVER_RUN_CONTEXT_SUBCMD: SUB.SERVER_RUN_CONTEXT,
  SERVER_RUN_REST_SUBCMD: SUB.SERVER_RUN_REST,
  SELF_STATE_APTITUDE_SUBCMD: SUB.SELF_STATE_APTITUDE,
  SELF_STATE_VALUE_UPDATE_SUBCMD: SUB.SELF_STATE_VALUE_UPDATE,
  SERVER_SCRIPT_IMMEDIATE_SUBCMD: SUB.SERVER_SCRIPT_IMMEDIATE,
  SERVER_SCRIPT_DEFERRED_SUBCMD: SUB.SERVER_SCRIPT_DEFERRED,

  // World
  ENABLE_DIALOG_EXPERIMENT: WORLD.ENABLE_DIALOG_EXPERIMENT,
  FORCE_START_SCENE: WORLD.FORCE_START_SCENE,
  MAP_ID: WORLD.MAP_ID,
  AREA_ID: WORLD.AREA_ID,
  ENTITY_TYPE: WORLD.ENTITY_TYPE,
  SPAWN_X: WORLD.SPAWN_X,
  SPAWN_Y: WORLD.SPAWN_Y,

  // Grouped exports for new TS consumers
  ENV,
  FRAMING,
  GAME_CMD,
  SUB,
  WORLD,
};
