'use strict';

module.exports = {
  PORT: 7777,
  LOG_FILE: 'server.log',
  CHARACTER_STORE_FILE: 'characters.json',
  MAX_PACKET_SIZE: 0x4000,
  VALID_FLAG_MASK: 0xe0,
  VALID_FLAG_VALUE: 0x40,
  DEFAULT_FLAGS: 0x40,
  SPECIAL_FLAGS: 0x44,
  LOGIN_CMD: 0x03e9,
  GAME_POSITION_QUERY_CMD: 0x03eb,
  GAME_DIALOG_CMD: 0x03e7,
  GAME_SERVER_RUN_CMD: 0x03f1,
  GAME_SELF_STATE_CMD: 0x03f6,
  GAME_SCRIPT_EVENT_CMD: 0x0407,
  GAME_SPAWN_BATCH_SUBCMD: 0x15,
  ROLE_CMD: 0x044c,
  HANDSHAKE_CMD: 1,
  PING_CMD: 2,
  PONG_CMD: 3,
  LINE_SELECT_RESULT: 0x1b,
  REDIRECT_RESULT: 0x0d,
  LOGIN_SERVER_LIST_RESULT: 0x03,
  SELF_STATE_APTITUDE_SUBCMD: 0x0a,
  SERVER_SCRIPT_IMMEDIATE_SUBCMD: 0x7a,
  SERVER_SCRIPT_DEFERRED_SUBCMD: 0x7b,
  ENABLE_DIALOG_EXPERIMENT: false,
  FORCE_START_SCENE: true,
  MAP_ID: 207,
  AREA_ID: 6101,
  ENTITY_TYPE: 0x3e9,
  SPAWN_X: 70,
  SPAWN_Y: 95,
  STATIC_NPCS_BY_MAP: {
    206: [
      {
        id: 3141,
        entityType: 3141,
        x: 57,
        y: 88,
        richSpawn: false,
        templateFlags: 0,
      },
      {
        id: 3325,
        entityType: 3325,
        x: 62,
        y: 82,
        richSpawn: false,
        templateFlags: 0,
      },
      {
        id: 3325001,
        entityType: 3325,
        x: 51,
        y: 94,
        richSpawn: false,
        templateFlags: 0,
      },
      {
        id: 3139,
        entityType: 3139,
        x: 27,
        y: 146,
        richSpawn: false,
        templateFlags: 0,
      },
      {
        id: 3139001,
        entityType: 3139,
        x: 111,
        y: 173,
        richSpawn: false,
        templateFlags: 0,
      },
      {
        id: 3140,
        entityType: 3140,
        x: 82,
        y: 76,
        richSpawn: false,
        templateFlags: 0,
      },
      {
        id: 3140001,
        entityType: 3140,
        x: 120,
        y: 52,
        richSpawn: false,
        templateFlags: 0,
      },
    ],
    207: [
      {
        id: 3141,
        entityType: 3141,
        x: 57,
        y: 88,
        richSpawn: false,
        templateFlags: 0,
      },
      {
        id: 3325,
        entityType: 3325,
        x: 62,
        y: 82,
        richSpawn: false,
        templateFlags: 0,
      },
      {
        id: 3325001,
        entityType: 3325,
        x: 51,
        y: 94,
        richSpawn: false,
        templateFlags: 0,
      },
      {
        id: 3139,
        entityType: 3139,
        x: 27,
        y: 146,
        richSpawn: false,
        templateFlags: 0,
      },
      {
        id: 3139001,
        entityType: 3139,
        x: 111,
        y: 173,
        richSpawn: false,
        templateFlags: 0,
      },
      {
        id: 3140,
        entityType: 3140,
        x: 82,
        y: 76,
        richSpawn: false,
        templateFlags: 0,
      },
      {
        id: 3140001,
        entityType: 3140,
        x: 120,
        y: 52,
        richSpawn: false,
        templateFlags: 0,
      },
    ],
    208: [
      {
        id: 3142,
        entityType: 3142,
        x: 115,
        y: 98,
        richSpawn: false,
        templateFlags: 0,
      },
      {
        id: 3144,
        entityType: 3144,
        x: 88,
        y: 138,
        richSpawn: false,
        templateFlags: 0,
      },
      {
        id: 3103,
        entityType: 3103,
        x: 57,
        y: 137,
        richSpawn: false,
        templateFlags: 0,
      },
      {
        id: 3136,
        entityType: 3136,
        x: 62,
        y: 132,
        richSpawn: false,
        templateFlags: 0,
      },
      {
        id: 3318,
        entityType: 3318,
        x: 122,
        y: 137,
        richSpawn: false,
        templateFlags: 0,
      },
      {
        id: 3315,
        entityType: 3315,
        x: 58,
        y: 79,
        richSpawn: false,
        templateFlags: 0,
      },
      {
        id: 3314,
        entityType: 3314,
        x: 66,
        y: 79,
        richSpawn: false,
        templateFlags: 0,
      },
      {
        id: 3147,
        entityType: 3147,
        x: 8,
        y: 127,
        richSpawn: false,
        templateFlags: 0,
      },
      {
        id: 3148,
        entityType: 3148,
        x: 6,
        y: 130,
        richSpawn: false,
        templateFlags: 0,
      },
      {
        id: 3320,
        entityType: 3320,
        x: 67,
        y: 163,
        richSpawn: false,
        templateFlags: 0,
      },
      {
        id: 3323,
        entityType: 3323,
        x: 101,
        y: 44,
        richSpawn: false,
        templateFlags: 0,
      },
      {
        id: 3323001,
        entityType: 3323,
        x: 105,
        y: 48,
        richSpawn: false,
        templateFlags: 0,
      },
      {
        id: 3324,
        entityType: 3324,
        x: 34,
        y: 128,
        richSpawn: false,
        templateFlags: 0,
      },
      {
        id: 3137,
        entityType: 3137,
        x: 101,
        y: 117,
        richSpawn: false,
        templateFlags: 0,
      },
      {
        id: 3326,
        entityType: 3326,
        x: 117,
        y: 129,
        richSpawn: false,
        templateFlags: 0,
      },
    ],
    209: [
      {
        id: 3142,
        entityType: 3142,
        x: 115,
        y: 98,
        richSpawn: false,
        templateFlags: 0,
      },
      {
        id: 3054,
        entityType: 3054,
        x: 117,
        y: 127,
        richSpawn: false,
        templateFlags: 0,
      },
    ],
  },
};
